### ISSUE TITLE
Failed to start org.geppetto.frontend bundle on virgo

### ISSUE THREAD

**Issue by skhayrulin** [openworm/org.geppetto.frontend#317]
Can anybody help me with it:
<DE0000I> Installing bundle 'org.geppetto.frontend' version '0.2.3'. 
[2015-07-08 02:14:55.006]  TCP Connection(4)-127.0.0.1 <DE0001I> Installed bundle 'org.geppetto.frontend' version '0.2.3'. 
[2015-07-08 02:14:55.031]  TCP Connection(4)-127.0.0.1 <DE0004I> Starting bundle 'org.geppetto.frontend' version '0.2.3'. 
[2015-07-08 02:14:55.033] start-signalling-1           <WE0000I> Starting web bundle 'org.geppetto.frontend' version '0.2.3' with context path '/org.geppetto.frontend'. 
[2015-07-08 02:14:55.043] start-signalling-1           <WE0004E> Failed to start web bundle 'org.geppetto.frontend' version '0.2.3': a web application with context path '/org.geppetto.frontend' already exists. 
[2015-07-08 02:14:55.048] start-signalling-1           <DE0006E> Start failed for bundle 'org.geppetto.frontend' version '0.2.3'. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Web application failed to start
	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:132)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStarted(StandardArtifactStateMonitor.java:271)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartSucceeded(AbstractInstallArtifact.java:319)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$0(AbstractInstallArtifact.java:316)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalSuccessfulCompletion(AbstractInstallArtifact.java:252)
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.gemini.web.core.WebApplicationStartFailedException: org.eclipse.gemini.web.core.spi.ContextPathExistsException: Context path '/org.geppetto.frontend' already exists
	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:137)
	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:122)
	... 8 common frames omitted
Caused by: org.eclipse.gemini.web.core.spi.ContextPathExistsException: Context path '/org.geppetto.frontend' already exists
	at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.checkContextPathIsFree(TomcatServletContainer.java:218)
	at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.startWebApplication(TomcatServletContainer.java:120)
	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
	... 9 common frames omitted

[2015-07-08 02:14:55.052] start-signalling-1           <DE0010I> Stopping bundle 'org.geppetto.frontend' version '0.2.3'. 
[2015-07-08 02:14:55.055] start-signalling-1           <DE0011I> Stopped bundle 'org.geppetto.frontend' version '0.2.3'. 
[2015-07-08 02:14:55.057]  TCP Connection(4)-127.0.0.1 <DE0013I> Uninstalling bundle 'org.geppetto.frontend' version '0.2.3'. 
[2015-07-08 02:14:55.064]  TCP Connection(4)-127.0.0.1 <DE0014I> Uninstalled bundle 'org.geppetto.frontend' version '0.2.3'. 

It hapens every time when I'm trying start virgo server in eclipse

**Comment by gidili** [comment]
@skhayrulin I've seen that a couple of times... it's like virgo thinks there is already another frontend bundle deployed with the same context path (url):

`Caused by: org.eclipse.gemini.web.core.spi.ContextPathExistsException: Context path '/org.geppetto.frontend' already exists`

Try doing a maven update and/or a maven install of frontend with the server running, this causes the bundle to do a hard redeploy and more often than not wipes away this kind of stuff. If that doesn't work try deleting the org.geppetto.frontend folder from the "stage" folder inside of virgo, and restart the server and do the steps above again.

Good luck!

**Comment by skhayrulin** [comment]
Hi @gidili thanks for help.
I've tried all but I have the same problem :(

**Comment by gidili** [comment]
@skhayrulin try removing the bundle from add/remove menu (right-clicking virgo from within eclipse), delete it again from the stage folder and start the server, if that works, re-add and see if it the error goes away.

@tarelli other ideas?

**Comment by skhayrulin** [comment]
I removed frontend bundle and run server and it started fine but when I add frontend bundle (server was working in thet time) again I had the same error

**Comment by tarelli** [comment]
@skhayrulin I'll send you an invitation for next Monday, I want to show you the new release of Geppetto that I'm working on releasing and what changed. We'll also solve the above in the process :)

**Comment by skhayrulin** [comment]
It would be great!! :+1: 
Thanks guys :)!

**Comment by skhayrulin** [comment]
@gidili @tarelli I've pulled all updates from development branches for all my geppetto projects than make maven install for all projects looks like everything fine but when I trying to run virgo I have following problem <a href="http://pastebin.com/FXwq2x68">log here</a>. Can you guys help me with it.

**Comment by gidili** [comment]
@skhayrulin you need to upgrade maven, I tried myself to update maven on my system and have eclipse point to the new one but I was getting strange errors so I gave up and switched to eclipse luna as it already has a higher version of maven embedded. 

The only problem with luna is installing the virgo tooling plugins (there are a few hurdles, you basically need to download the plugin from the dev builds and install it manually...), @tarelli helped me do that. We can do a meeting soon to do it together maybe and we can use it as an excuse to document the trick.

**Comment by skhayrulin** [comment]
@gidili thanks, sounds good

**Comment by tarelli** [comment]
Installed the latest with @skhayrulin, working now
