### ISSUE TITLE
Issues with minimised/production site code for popup widget

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#593]
getting:
```console
main.bundle.js:116 Uncaught TypeError: Cannot read property 'getMetaType' of undefined
    at Object.populateTypeReferences (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:26845)
    at Object.populateTypeReferences (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:28099)
    at Object.populateTypeReferences (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:28099)
    at Object.mergeModel (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:117:1584)
    at Object.addVariableToModel (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:15588)
    at Object.messageHandler.(anonymous function) [as variable_fetched] (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:9092)
    at Object.onMessage (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:12852)
    at r (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:20532)
    at WebSocket.t.MessageSocket.socket.onmessage (https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:116:21619)
```

Which relates to ```s.getMetaType() == GEPPETTO.Resources.POINTER_TYPE``` in:
```javascript
populateTypeReferences: function(t) {
                    if (t.getMetaType() == GEPPETTO.Resources.VARIABLE_NODE) {
                        var e = t.getTypes()
                          , n = []
                          , r = !1
                          , i = !0;
                        if (void 0 != e) {
                            for (var o = 0; o < e.length; o++) {
                                if (e[o]instanceof Type) {
                                    i = !1;
                                    break
                                }
                                var a = e[o].$ref;
                                if (void 0 != a) {
                                    var s = this.resolve(a);
                                    s.getMetaType() == GEPPETTO.Resources.POINTER_TYPE && (r = !0),
                                    n.push(s)
                                }
                            }
                            i && t.setTypes(n)
                        }
```

Which is derived from:
https://github.com/openworm/org.geppetto.frontend/blob/query/src/main/webapp/js/geppettoModel/ModelFactory.js#L184

This can be replicated by opening:
- https://v2a.virtualflybrain.org/
- selecting the main brain 
- clicking on an example image (painted domain)

**Comment by Robbie1977** [comment]
@gidili any ideas on this one as doesn't seem to occur in the non-production deployment.

**Comment by gidili** [comment]
@Robbie1977 100% sure it's the exact same data? Very weird never seen anything like that break because of minification.

Am I clicking on the right example (clicked painted domain JFRC2 after selecting main brain)? Not seeing errors in console:
<img width="1275" alt="screenshot 2017-04-28 13 15 15" src="https://cloud.githubusercontent.com/assets/68134/25528260/ca0c51d6-2c14-11e7-91a2-ef7e7a8b4b8b.png">

**Comment by Robbie1977** [comment]
What version of chrome are you testing with? 

Getting the same result in chrome under windows and macOS but latest version.

**Comment by gidili** [comment]
@Robbie1977 Using this version:
<img width="272" alt="screenshot 2017-04-29 17 51 57" src="https://cloud.githubusercontent.com/assets/68134/25557212/027f9956-2d05-11e7-8133-d494af4e64b9.png">

Tried a few more painted domain examples and still nothing:
<img width="1286" alt="screenshot 2017-04-29 17 55 01" src="https://cloud.githubusercontent.com/assets/68134/25557214/0efb5508-2d05-11e7-8892-5dcfe97a6f7e.png">

@tarelli can you try too?

**Comment by Robbie1977** [comment]
Interesting twist I don't seem to get the error on a incognito window so suspect it maybe an extension causing the issue so will work through them but happy to close unless anyone else sees it.
